version: '3.8'

# api and mysql service
services:
  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    
    
    

volumes:
  db_data:
    driver: local
